name: Check Camping Availability

on:
  schedule:
    # 15分ごとに実行（UTCタイムゾーン）
    - cron: '*/15 * * * *'
  workflow_dispatch: # 手動実行用

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check availability
        run: |
          curl -X GET "https://camping-reservation-bot-new.vercel.app/api/check-availability"
        continue-on-error: true # エラーが発生しても続行
      
      - name: Report status
        run: |
          echo "Availability check completed at $(date)"